doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    namespace: IVIR3zaM\OrganizationRelationships\Migrations
    table_name: 'migration_versions'
    name: 'Application Migrations'
    organize_migrations: false
